### ISSUE TITLE
I RAN OUT OF SALAD

### ISSUE THREAD

**Issue by charliecurtin1** [CASAschools/salad_recipe#1]
i ran out of salad stuff can you actually bring the salad

**Comment by charliecurtin1** [comment]
@lchenhub bring salad

- [] yes
- [] yes

**Comment by lchenhub** [comment]
[] NOPE

**Comment by lchenhub** [comment]
dandelions are free

**Comment by charliecurtin1** [comment]
ok great no salad thats just dandy
